#!/bin/bash
cp ~/.config/mpv/*.conf ./.config/mpv/
cp ~/.bashrc .

directories=("chadwm" "zathura" "rofi" "nvim" "alacritty")

for directory in ${directories}
do
  rm -rf ./.config/$directory
  cp -r ~/.config/$directory ./.config/
done;

git add .
git commit -m "update dots"
git push origin main
