#!/bin/bash

if [ "$1" = "prev" ]; then
  playerctl previous;
elif [ "$1" = "next" ]; then
  playerctl next
elif [ "$1" = "play-pause" ]; then
  players=("elisa" "firefox.instance2")

  if playerctl -a status 2>&1 | grep -q "Playing"; then
    playerctl -a pause
  else
    for player in "${players[@]}"
    do
      if playerctl --list-all | grep -q "$player"; then
        playerctl --player="$player" play
        exit 0
      fi
    done
    playerctl play
  fi
fi
