#!/bin/bash
. ~/.config/chadwm/scripts/bar_themes/tokyonight

vol=$(pactl get-sink-volume "reverse-stereo" | grep '^Volume:' | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,')
num="5"

if [ printf "$vol" | grep -q "[0-9]" ]; then
  printf " "
  exit
fi

mod="$(printf "$vol / $num \n" | bc )"
active=$(printf "%.s█" $(seq "$mod"))
non="$(printf "%.s▒" $(seq $(printf "100 / $num - $mod\n" | bc)))"

printf "^c$white^ $vol%% $active$non^b$black^ "
