#!/bin/bash
. ~/.config/chadwm/scripts/bar_themes/tokyonight

vol=$(pactl get-sink-volume $(pactl get-default-sink) | grep '^Volume:' | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,')
num="5"

if printf "$vol" | grep -qv "[0-9]"; then
  printf " "
  exit
fi

mod="$(printf "$vol / $num \n" | bc )"
active=$(printf "%.s█" $(seq "$mod"))
p=$(printf "100 / $num - $mod\n" | bc)
if expr $vol "<" 100 >> /dev/null; then 
  non="$(printf "%.s▒" $(seq "$p"))"
fi;
printf "^c$white^ $vol%% $active$non "
